"""
Environmental savings interface.

Module 7.4
----------
Provides the Streamlit presentation layer for displaying
environmental impact metrics generated by the FastAPI backend.

All environmental calculations remain owned by the backend
environmental savings engine.
"""

from __future__ import annotations

from typing import Any

import streamlit as st

from src.streamlit_app.api_client import (
    APIClient,
    APIClientError,
)


def _extract_recommendations(
    response: dict[str, Any],
) -> list[dict[str, Any]]:
    """Extract environmental recommendation records from the API response."""
    recommendations = response.get("recommendations", [])

    if not isinstance(recommendations, list):
        return []

    return recommendations


def _extract_summary(
    response: dict[str, Any],
) -> dict[str, Any]:
    """Extract the environmental summary from the API response."""
    summary = response.get("environmental_summary", {})

    if not isinstance(summary, dict):
        return {}

    return summary


def _format_recommendations(
    recommendations: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """
    Prepare environmental recommendation records for presentation.

    This function only maps API response fields to presentation
    labels. It does not calculate environmental metrics.
    """
    rows: list[dict[str, Any]] = []

    for recommendation in recommendations:
        rows.append(
            {
                "Rank": recommendation.get("rank"),
                "Source Material": recommendation.get(
                    "source_material_name"
                ),
                "Process": recommendation.get("process_name"),
                "Target Material": recommendation.get(
                    "target_material"
                ),
                "Demand": recommendation.get(
                    "demand_material_name"
                ),
                "Carbon Footprint (kg CO2e)": recommendation.get(
                    "carbon_footprint_kg_co2e"
                ),
                "Recycling Footprint (kg CO2e)": recommendation.get(
                    "recycling_footprint_kg_co2e"
                ),
                "Carbon Savings (kg CO2e)": recommendation.get(
                    "carbon_savings_kg_co2e"
                ),
                "Savings (%)": recommendation.get(
                    "carbon_savings_percentage"
                ),
            }
        )

    return rows


def render_environmental_savings(
    client: APIClient,
) -> None:
    """Render the environmental savings interface."""

    st.subheader("Environmental Savings")

    st.write(
        "Evaluate carbon footprint, recycling footprint, "
        "and carbon savings generated by the recommended "
        "recycling pathways."
    )

    if st.button(
        "🌱 Calculate Environmental Savings",
        type="primary",
        use_container_width=True,
    ):
        try:
            with st.spinner(
                "Loading environmental impact..."
            ):
                response = client.get_environmental_impact()

        except APIClientError as exc:
            st.error(
                "Unable to load environmental savings."
            )
            st.caption(str(exc))
            return

        recommendations = _extract_recommendations(
            response
        )

        summary = _extract_summary(response)

        st.divider()

        if not recommendations:
            st.info(
                "No environmental savings data is "
                "currently available."
            )
            return

        st.subheader("Overall Environmental Impact")

        metric_col1, metric_col2 = st.columns(2)

        with metric_col1:
            st.metric(
                label="Recommendations",
                value=summary.get(
                    "recommendation_count",
                    response.get(
                        "count",
                        len(recommendations),
                    ),
                ),
            )

        with metric_col2:
            st.metric(
                label="Available Quantity",
                value=summary.get(
                    "total_available_quantity",
                    0,
                ),
            )

        metric_col3, metric_col4 = st.columns(2)

        with metric_col3:
            st.metric(
                label="Carbon Footprint",
                value=(
                    f"{summary.get('total_carbon_footprint_kg_co2e', 0):,.2f} "
                    "kg CO2e"
                ),
            )

        with metric_col4:
            st.metric(
                label="Recycling Footprint",
                value=(
                    f"{summary.get('total_recycling_footprint_kg_co2e', 0):,.2f} "
                    "kg CO2e"
                ),
            )

        metric_col5, metric_col6 = st.columns(2)

        with metric_col5:
            st.metric(
                label="Carbon Savings",
                value=(
                    f"{summary.get('total_carbon_savings_kg_co2e', 0):,.2f} "
                    "kg CO2e"
                ),
            )

        with metric_col6:
            st.metric(
                label="Overall Savings",
                value=(
                    f"{summary.get('overall_carbon_savings_percentage', 0):,.2f}%"
                ),
            )

        st.divider()

        st.subheader(
            "Environmental Impact by Recommendation"
        )

        rows = _format_recommendations(
            recommendations
        )

        st.dataframe(
            rows,
            use_container_width=True,
            hide_index=True,
        )

        st.divider()

        st.caption(
            "Environmental metrics are generated by the "
            "FastAPI environmental savings engine."
        )