"""
Compatibility recommendation interface.

Module 7.3
----------
Provides the Streamlit presentation layer for displaying
recommendations generated by the FastAPI backend.

All recommendation scoring and ranking remain owned by the
backend recommendation engine.
"""

from __future__ import annotations

from typing import Any

import streamlit as st

from src.streamlit_app.api_client import (
    APIClient,
    APIClientError,
)


def _extract_recommendations(
    response: dict[str, Any],
) -> list[dict[str, Any]]:
    """Extract recommendation records from the API response."""
    recommendations = response.get("recommendations", [])

    if not isinstance(recommendations, list):
        return []

    return recommendations


def _format_recommendations(
    recommendations: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """
    Prepare recommendation records for presentation.

    This function only formats API data. It does not calculate
    compatibility scores, ranking, or business metrics.
    """
    rows: list[dict[str, Any]] = []

    for recommendation in recommendations:
        rows.append(
            {
                "Rank": recommendation.get("rank"),
                "Source Material": recommendation.get(
                    "source_material_name"
                ),
                "Process": recommendation.get("process_name"),
                "Target Material": recommendation.get(
                    "target_material"
                ),
                "Demand": recommendation.get(
                    "demand_material_name"
                ),
                "Compatibility Score": recommendation.get(
                    "compatibility_score"
                ),
                "Quantity Coverage": recommendation.get(
                    "quantity_coverage_ratio"
                ),
            }
        )

    return rows


def render_recommendations(client: APIClient) -> None:
    """Render the compatibility recommendation interface."""
    st.subheader("Compatibility Recommendations")

    st.write(
        "View ranked reuse, recycling, and remanufacturing "
        "matches generated by the recommendation engine."
    )

    if st.button(
        "🎯 Generate Recommendations",
        type="primary",
        use_container_width=True,
    ):
        try:
            with st.spinner("Generating recommendations..."):
                response = client.get_recommendations()
        except APIClientError as exc:
            st.error("Unable to generate recommendations.")
            st.caption(str(exc))
            return

        recommendations = _extract_recommendations(response)

        st.divider()

        st.metric(
            label="Recommendations",
            value=response.get(
                "count",
                len(recommendations),
            ),
        )

        if not recommendations:
            st.info(
                "No compatibility recommendations are "
                "currently available."
            )
            return

        rows = _format_recommendations(
            recommendations
        )

        st.dataframe(
            rows,
            use_container_width=True,
            hide_index=True,
        )

        st.divider()

        st.caption(
            "Compatibility scores and ranking are generated "
            "by the FastAPI recommendation engine."
        )